version: '3.8'

services:
  # Database Service
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-trackit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-trackit}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trackit} -d ${POSTGRES_DB:-trackit}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  # Cache Service
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/piwi3910/trackit-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-trackit}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-trackit}?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      PORT: 3001
      CORS_ORIGIN: ${CORS_ORIGIN:-https://trackit.azrty.com}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-.azrty.com}
      SECURE_COOKIES: ${SECURE_COOKIES:-true}
      SAME_SITE: ${SAME_SITE:-strict}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - backend-network
      - frontend-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://trackit.azrty.com/api/trpc}
        VITE_APP_URL: ${VITE_APP_URL:-https://trackit.azrty.com}
        VITE_WS_URL: ${VITE_WS_URL:-wss://trackit.azrty.com/ws}
    image: ghcr.io/piwi3910/trackit-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - frontend-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local