version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: trackituser
      POSTGRES_PASSWORD: trackitpassword
      POSTGRES_DB: trackit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: