apiVersion: v1
kind: Secret
metadata:
  name: trackit-secrets
  namespace: trackit
  labels:
    app: trackit
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "trackit"
  POSTGRES_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
  POSTGRES_DB: "trackit"
  
  # JWT secrets - MUST be changed in production
  JWT_SECRET: "CHANGE_ME_PRODUCTION_JWT_SECRET_MIN_32_CHARS"
  JWT_REFRESH_SECRET: "CHANGE_ME_PRODUCTION_JWT_REFRESH_SECRET_MIN_32_CHARS"
  
  # Session secret
  SESSION_SECRET: "CHANGE_ME_PRODUCTION_SESSION_SECRET_MIN_32_CHARS"
  
  # Google OAuth credentials (optional)
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  
  # Email service credentials (optional)
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: "noreply@trackit.azrty.com"
  
  # Encryption keys
  ENCRYPTION_KEY: "CHANGE_ME_32_BYTE_ENCRYPTION_KEY"