apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: trackit
  labels:
    app: trackit
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trackit
      component: backend
  template:
    metadata:
      labels:
        app: trackit
        component: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: backend
        image: ghcr.io/piwi3910/trackit-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
          name: http
        command:
        - /bin/sh
        - -c
        - |
          # URL encode the password to handle special characters
          ENCODED_PASSWORD=$(echo -n "${POSTGRES_PASSWORD}" | sed 's/\//%2F/g' | sed 's/:/%3A/g' | sed 's/@/%40/g')
          export DATABASE_URL="postgresql://${DATABASE_USER}:${ENCODED_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public"
          cd /app/backend && node dist/server.js
        envFrom:
        - configMapRef:
            name: trackit-config
        - secretRef:
            name: trackit-secrets
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: trackit
  labels:
    app: trackit
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: trackit
    component: backend