apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trackit-ingress
  namespace: trackit
  labels:
    app: trackit
  annotations:
    # Use existing cert-manager issuer
    cert-manager.io/cluster-issuer: letsencrypt-prod
    
    # SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
    # WebSocket support
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' wss://trackit.azrty.com https://apis.google.com; frame-src https://accounts.google.com";
      more_set_headers "Permissions-Policy: geolocation=(), microphone=(), camera=()";
    
    # Body size for file uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    
    # Backend protocol
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    
    # Rewrite for API
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - trackit.azrty.com
    secretName: trackit-tls
  rules:
  - host: trackit.azrty.com
    http:
      paths:
      # API routes - strip /api prefix
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3001
      # Health check
      - path: /health
        pathType: Exact
        backend:
          service:
            name: backend-service
            port:
              number: 3001
      # Frontend routes (catch-all)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80