apiVersion: batch/v1
kind: Job
metadata:
  name: trackit-migrate
  namespace: trackit
  labels:
    app: trackit
    component: migration
spec:
  template:
    metadata:
      labels:
        app: trackit
        component: migration
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: migrate
        image: ghcr.io/piwi3910/trackit-backend:latest
        imagePullPolicy: IfNotPresent
        command: 
        - /bin/sh
        - -c
        - |
          # URL encode the password to handle special characters
          ENCODED_PASSWORD=$(echo -n "${POSTGRES_PASSWORD}" | sed 's/\//%2F/g' | sed 's/:/%3A/g' | sed 's/@/%40/g')
          export DATABASE_URL="postgresql://${DATABASE_USER}:${ENCODED_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public"
          npm run migrate:deploy
        envFrom:
        - configMapRef:
            name: trackit-config
        - secretRef:
            name: trackit-secrets