apiVersion: batch/v1
kind: Job
metadata:
  name: trackit-seed
  namespace: trackit
  labels:
    app: trackit
spec:
  template:
    metadata:
      labels:
        app: trackit
        job: seed
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: seed
        image: ghcr.io/piwi3910/trackit-backend:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          # URL encode the password to handle special characters
          ENCODED_PASSWORD=$(echo -n "${POSTGRES_PASSWORD}" | sed 's/\//%2F/g' | sed 's/:/%3A/g' | sed 's/@/%40/g')
          export DATABASE_URL="postgresql://${DATABASE_USER}:${ENCODED_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public"
          cd /app/backend
          # Run seed script
          npx prisma db seed
        envFrom:
        - configMapRef:
            name: trackit-config
        - secretRef:
            name: trackit-secrets
        env:
        - name: NODE_ENV
          value: "development"