apiVersion: v1
kind: Pod
metadata:
  name: debug-backend
  namespace: trackit
spec:
  containers:
  - name: debug
    image: ghcr.io/piwi3910/trackit-backend:latest
    command: ["sh", "-c", "sleep 3600"]
    envFrom:
    - configMapRef:
        name: trackit-config
    - secretRef:
        name: trackit-secrets